In [1]:
# 使用pip安装PyTorch
# pip install torch torchvision

import torch

# 基本操作

In [2]:
# 创建一个未初始化的张量
x = torch.empty(5, 3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [3]:
# 创建一个随机初始化的张量
y = torch.rand(5, 3)
print(y)

tensor([[0.9926, 0.7192, 0.1602],
        [0.8161, 0.2519, 0.4422],
        [0.9083, 0.7860, 0.6426],
        [0.2171, 0.1131, 0.2514],
        [0.1167, 0.1004, 0.4975]])


In [4]:
# 创建一个全零矩阵
z = torch.zeros(5, 3, dtype=torch.long)
print(z)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [5]:
# 创建一个直接从数据列表构造的张量
w = torch.tensor([[1.0, -1.0], [2.0, -2.0]])
print(w)

tensor([[ 1., -1.],
        [ 2., -2.]])


In [6]:
# 张量的属性
print(w.size()) # .size() 已经被弃用，建议使用 .shape
print(w.shape) # 推荐的方式
print(w.dtype) # 数据类型

torch.Size([2, 2])
torch.Size([2, 2])
torch.float32


In [7]:
# 张量操作
a = torch.tensor([1., 2., 3.])
b = torch.tensor([4., 5., 6.])
print(a + b) # 加法
print(torch.add(a, b)) # 加法的另一种方式

tensor([5., 7., 9.])
tensor([5., 7., 9.])


In [8]:
# 使用NumPy数组创建张量
import numpy as np
np_array = np.array([[1, 2], [3, 4.]])
t = torch.from_numpy(np_array)
print(t)

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)


In [9]:
# 创建一个随机张量
v1 = torch.rand(2, 3, requires_grad=True)
print("Original Tensor:")
print(v1)

# 尝试直接转换为 NumPy 数组（如果v1在GPU上或涉及到梯度计算，这行会报错）
try:
    np_v1 = v1.numpy()
    print("Converted to NumPy array without detach:")
    print(np_v1)
except RuntimeError as e:
    print("Error:", e)

# 正确的方式，确保张量不在计算图中且在CPU上
np_v1 = v1.detach().cpu().numpy()
print("Converted to NumPy array with detach and moved to CPU:")
print(np_v1)

Original Tensor:
tensor([[0.1430, 0.2601, 0.0692],
        [0.0160, 0.5036, 0.7079]], requires_grad=True)
Error: Can't call numpy() on Tensor that requires grad. Use tensor.detach().numpy() instead.
Converted to NumPy array with detach and moved to CPU:
[[0.14295101 0.26011157 0.06915587]
 [0.01603687 0.5035888  0.707906  ]]


# 自动计算梯度

In [2]:
import torch

In [3]:
x = torch.ones(2, 2, requires_grad=True)  # 告诉 PyTorch 需要计算这个张量的梯度
y = x + 2
z = y * y * 3
out = z.mean()  # 计算张量 z 的所有元素的平均值，得到一个标量

out.backward() # 计算梯度

print(x.grad) # 输出梯度

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


# 神经网络模块（nn.Module）

In [4]:
import torch
import torch.nn as nn
import torch.nn.functional as F

class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.fc1 = nn.Linear(2, 1)

    def forward(self, x):
        x = F.relu(self.fc1(x))
        return x

net = Net()

# 打印网络结构
print(net)

# 输入一个随机的张量
input = torch.randn(1, 2)
print("Input:\n", input)

# 获取网络的输出
output = net(input)
print("Output:\n", output)

# 打印所有的参数
for name, param in net.named_parameters():
    print ("="*30)
    print(f"Layer: {name}, Param: {param}, Requires_grad: {param.requires_grad}")

Net(
  (fc1): Linear(in_features=2, out_features=1, bias=True)
)
Input:
 tensor([[0.4856, 0.7791]])
Output:
 tensor([[0.]], grad_fn=<ReluBackward0>)
Layer: fc1.weight, Param: Parameter containing:
tensor([[ 0.4339, -0.4089]], requires_grad=True), Requires_grad: True
Layer: fc1.bias, Param: Parameter containing:
tensor([0.0808], requires_grad=True), Requires_grad: True


## 一个隐藏层

In [6]:
import torch
import torch.nn as nn
import torch.nn.functional as F

# 修改后的网络结构
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        # 添加一个隐藏层，输入特征为2，隐藏层特征为3
        self.fc1 = nn.Linear(2, 3)
        # 添加一个输出层，隐藏层特征为5，输出特征为3
        self.fc2 = nn.Linear(3, 2)

    def forward(self, x):
        # 使用ReLU激活函数处理隐藏层的输出
        x = F.relu(self.fc1(x))
        # 处理输出层的输出
        x = self.fc2(x)
        return x

# 实例化网络
net = Net()

# 打印网络结构
print(net)

# 输入一个随机的张量
input = torch.randn(1, 2)
print("Input:\n", input)

# 获取网络的输出
output = net(input)
print("Output:\n", output)

# 打印所有的参数
for name, param in net.named_parameters():
    print ("="*30)
    print(f"Layer: {name}, Param: {param}, Requires_grad: {param.requires_grad}")


Net(
  (fc1): Linear(in_features=2, out_features=3, bias=True)
  (fc2): Linear(in_features=3, out_features=2, bias=True)
)
Input:
 tensor([[-0.4912,  0.3828]])
Output:
 tensor([[-0.3606,  0.3850]], grad_fn=<AddmmBackward0>)
Layer: fc1.weight, Param: Parameter containing:
tensor([[ 0.3640,  0.3488],
        [-0.3150, -0.2339],
        [ 0.7009, -0.3358]], requires_grad=True), Requires_grad: True
Layer: fc1.bias, Param: Parameter containing:
tensor([ 0.6362, -0.0496, -0.3305], requires_grad=True), Requires_grad: True
Layer: fc2.weight, Param: Parameter containing:
tensor([[-0.5282, -0.0131,  0.3920],
        [ 0.1203, -0.1582, -0.2640]], requires_grad=True), Requires_grad: True
Layer: fc2.bias, Param: Parameter containing:
tensor([-0.0482,  0.3163], requires_grad=True), Requires_grad: True


# 优化器（Optimizer）

In [11]:
import torch
import torch.nn as nn
import torch.nn.functional as F

# 定义网络
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.fc1 = nn.Linear(2, 1)  # 输入特征为2，输出特征为1

    def forward(self, x):
        x = F.relu(self.fc1(x))
        return x

# 实例化网络
net = Net()

# 随机生成输入数据
input = torch.randn(1, 2)  # 一个样本，两个特征
print("Input:\n", input)

# 随机生成目标数据（对于回归问题）
target = torch.randn(1, 1)  # 一个样本，一个特征（假设）
print("Target:\n", target)

# 或者如果是分类问题，目标可以是这样的：
# target = torch.tensor([0])  # 假设只有两个类别，这里的目标是第一个类别

# 定义损失函数
criterion = nn.MSELoss()  # 均方误差损失函数

# 定义优化器
optimizer = torch.optim.SGD(net.parameters(), lr=0.01)

# 清空梯度缓存
optimizer.zero_grad()

# 前向传播
output = net(input)
print("Output before backward pass:\n", output)

# 计算损失
loss = criterion(output, target)
print("Loss:\n", loss.item())

# 反向传播
loss.backward()

# 更新参数
optimizer.step()

# 再次前向传播，查看更新后的输出
output_after_update = net(input)
print("Output after one step of gradient descent:\n", output_after_update)

Input:
 tensor([[ 0.9711, -0.6973]])
Target:
 tensor([[-0.2845]])
Output before backward pass:
 tensor([[0.1210]], grad_fn=<ReluBackward0>)
Loss:
 0.16444812715053558
Output after one step of gradient descent:
 tensor([[0.1013]], grad_fn=<ReluBackward0>)
